# netlify.toml

[build]
  # This is the command Netlify will run to build your site.
  command = "npm run build"
  
  # For Next.js, it's the .next folder.
  publish = ".next"

# how to correctly handle server components, image optimization, etc.
[functions]
  directory = ".next/functions"
<<<<<<< HEAD


  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
>>>>>>> 0355f401bcfdd54fc9fe3da50390a2ed891e1b1d
